### ISSUE TITLE
atoi(3) considered harmful

### ISSUE THREAD

**Issue by ghost** [shamoanjac/cchan#7]
atoi(3) is a harmful library function and should not be used. if it does not encounter an integer in the first part of a string it simply returns 0.

the problem can be seen more clearly by running this code snippet:

```c
#include <stdlib.h>
#include <stdio.h>

int
main(void)
{
	const char *number = "1917";
	const char *named = "Vladimir Lenin";
	const char *zero = "0";

	printf("%s: %d\n", number, atoi(number));
	printf("%s: %d\n", zero, atoi(zero));
	printf("%s: %d\n", named, atoi(named));

	return 0;
}
```

its use should be replaced with strtol(3) present in glibc or strtonum(3) present in the openbsd libc and in libbsd.

**Comment by shamoanjac** [comment]
In the context in which atoi() is used, the worst that happens is that C-chan will try to bind the server socket to the port 0. Which will just result in a failure. However, further utilizations of string parsing will most probably not use atoi(). It seems just fine to me in the main() function.
Plus, strtol() also results in undefined behaviour, and strtonum() is not an ANSI function.

Thanks for the insight, though.
